#!/bin/bash

set -eux

pushd "$(dirname ${0})"

go build --tags local

source credentials

# export HTTPS_PROXY=https://127.0.0.1:8080

# go server requires the gcloud CLI to be logged in with `gcloud auth application-default login`
./goserver


# Error: The Environment Variables provided for your Serverless Functions exceed the limit of 4KB. Reduce their size to continue. Learn More: https://vercel.link/env-vars-limit

